### ISSUE TITLE
Internal Server Error when LDAP server not availiable

### ISSUE THREAD

**Issue by individual-it** [owncloud/user_management#136]
When the LDAP app is installed but the configured server is not available the user_managment app crashes with an internal server error
```
{"reqId":"QLMuWCUbMLpu60KB1dHh","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/user_management\/","message":"No DN found for <admin> on localhost2"}
{"reqId":"QLMuWCUbMLpu60KB1dHh","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/user_management\/","message":"getGroups getGroups--500-"}
{"reqId":"QLMuWCUbMLpu60KB1dHh","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/user_management\/","message":"getGroups Filter (&(&(|(objectclass=posixGroup)))(cn=*))"}
{"reqId":"QLMuWCUbMLpu60KB1dHh","level":3,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"GET","url":"\/owncloud-core\/index.php\/apps\/user_management\/","message":"Exception: {\"Exception\":\"OC\\\\ServerNotAvailableException\",\"Message\":\"Lost connection to LDAP server.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(293): OCA\\\\User_LDAP\\\\LDAP->postFunctionCall()\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php(43): OCA\\\\User_LDAP\\\\LDAP->invokeLDAPMethod(*** sensitive parameters replaced ***)\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(540): OCA\\\\User_LDAP\\\\LDAP->bind(*** sensitive parameters replaced ***)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(169): OCA\\\\User_LDAP\\\\Connection->establishConnection()\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Connection.php(178): OCA\\\\User_LDAP\\\\Connection->init()\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(1004): OCA\\\\User_LDAP\\\\Connection->getConnectionResource()\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(1194): OCA\\\\User_LDAP\\\\Access->executeSearch('(&(&(|(objectcl...', Array, Array, 500, NULL)\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(957): OCA\\\\User_LDAP\\\\Access->search('(&(&(|(objectcl...', Array, Array, 500, NULL)\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(837): OCA\\\\User_LDAP\\\\Access->searchGroups('(&(&(|(objectcl...', Array, 500, NULL)\\n#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Group_LDAP.php(808): OCA\\\\User_LDAP\\\\Access->fetchListOfGroups('(&(&(|(objectcl...', Array, 500, NULL)\\n#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Group_LDAP.php(847): OCA\\\\User_LDAP\\\\Group_LDAP->getGroupsChunk('', 500, NULL)\\n#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/Group_Proxy.php(169): OCA\\\\User_LDAP\\\\Group_LDAP->getGroups('', NULL, NULL)\\n#12 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Group\\\/Manager.php(247): OCA\\\\User_LDAP\\\\Group_Proxy->getGroups('', NULL, NULL)\\n#13 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_management\\\/lib\\\/MetaData.php(188): OC\\\\Group\\\\Manager->search('', NULL, NULL, 'management')\\n#14 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_management\\\/lib\\\/MetaData.php(90): OCA\\\\UserManagement\\\\MetaData->getGroups('')\\n#15 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_management\\\/lib\\\/Controller\\\/PageController.php(88): OCA\\\\UserManagement\\\\MetaData->get()\\n#16 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\UserManagement\\\\Controller\\\\PageController->index()\\n#17 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\UserManagement\\\\Controller\\\\PageController), 'index')\\n#18 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\UserManagement\\\\Controller\\\\PageController), 'index')\\n#19 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\UserManagem...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#20 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#21 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php(906): OC\\\\Route\\\\Router->match('\\\/apps\\\/user_mana...')\\n#22 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/index.php(54): OC::handleRequest()\\n#23 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/user_ldap\\\/lib\\\/LDAP.php\",\"Line\":324}"}
{"reqId":"WBJaIXE8JPHHXXjARWNG","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/user_management\/undefined\/img\/notifications.svg","message":"No DN found for <admin> on localhost2"}
{"reqId":"YDlWBBxQhJSWw7dbojJM","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"No DN found for <admin> on localhost2"}
{"reqId":"8lvTgzt8B2mrYNn9nixl","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/files\/","message":"No DN found for <admin> on localhost2"}
{"reqId":"GiutM32Nj1FRWluLelqR","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/user_management\/undefined\/img\/notifications.svg","message":"No DN found for <admin> on localhost2"}
{"reqId":"Veayiycgi6vbMsQP1FjO","level":0,"time":"2019-01-28T07:51:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"user_ldap","method":"GET","url":"\/owncloud-core\/index.php\/apps\/files\/","message":"No DN found for <admin> on localhost2"}

**Comment by PVince81** [comment]
is this also visible on stable10 ?

**Comment by individual-it** [comment]
@PVince81 just tested with 10.1.0RC2 and user_ldap from the marketplace and same effect when trying to access the users page, even it does not use this app but the build in one
